apiVersion: v1
kind: Service
metadata:
  name: electrolite-user-service
spec:
  type: NodePort
  selector:
    app: electrolite-user-image
  ports:
    - nodePort: 31479
      port: 8080
      targetPort: 9000